/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package test;

import java.io.FileWriter;
import java.io.IOException;
import java.sql.Array;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
 

/**
 *
 * @author swetha kantheti
 */
public class videos extends javax.swing.JFrame {

    /**
     * Creates new form videos
     */
    void checkconnection(){
    if(new netconnection().connection()){
                this.setVisible(false);
            new SimpleSwingBrowser1().main(null);
            }
    }
    public static String uname="";
    public videos() {
        initComponents();
        checkconnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1390, 768));
        getContentPane().setLayout(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 210, 570, 310);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Rating");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 540, 70, 30);

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Best");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(20, 570, 70, 23);

        jRadioButton2.setText("Good");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(110, 570, 80, 23);

        jRadioButton3.setText("Average");
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(200, 570, 100, 23);

        jRadioButton4.setText("Below average");
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(320, 570, 140, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("search a video ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(590, 230, 110, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(730, 220, 190, 40);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(730, 280, 47, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Post your question ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(590, 370, 130, 14);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(720, 360, 200, 40);

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(720, 420, 50, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Comments ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(590, 480, 90, 15);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(710, 470, 300, 96);

        jButton3.setText("Submit  ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(720, 610, 110, 23);

        jLabel6.setFont(new java.awt.Font("Freestyle Script", 1, 36)); // NOI18N
        jLabel6.setText("Predictable Convergant Solutions");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 130, 580, 70);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Video name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(970, 360, 80, 30);

        jTextField3.setText(" ");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(1080, 350, 190, 40);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Search Results" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(970, 220, 190, 40);

        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1160, 100, 110, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/a.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1440, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //------------------------------------
        checkconnection();
         String comment=jTextArea1.getText();
        String VName=jTextField3.getText();
         try{
		    FileWriter fw=new FileWriter("offlinecomments.txt",true);
                  //  fw.write("ID:"+uname+"\n");
                    fw.write(VName+"\n");
                    fw.write(comment);
                    fw.close();
		  } catch (IOException ex) {
            Logger.getLogger(Staticforum.class.getName()).log(Level.SEVERE, null, ex);
        }
	
        commentthread c=new commentthread(uname);
        c.start();
        this.setVisible(false);
        //------------------------------------
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //------------------------------------
        checkconnection();
         String ques=jTextField2.getText();
        String VName=jTextField3.getText();
         try{
		    FileWriter fw=new FileWriter("offlinemessages.txt",true);
                  //  fw.write("ID:"+uname+"\n");
                    fw.write(VName+"\n");
                    fw.write(ques);
                    fw.close();
		  } catch (IOException ex) {
            Logger.getLogger(Staticforum.class.getName()).log(Level.SEVERE, null, ex);
        }
	
        forumthread f=new forumthread(uname);
        f.start();
        this.setVisible(false);
        //------------------------------------
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        checkconnection();
        String key=jTextField1.getText();
        String s1,s2,s3;
        ArrayList values= new ArrayList();
              
        
        int i=0;
        System.out.println("name"+key);
        try{
        Connection con=DatabaseConnection.dbConnection();
        PreparedStatement pst1=con.prepareStatement("Select * from videos");
        
         ResultSet rss=pst1.executeQuery();
                while(rss.next()){
                    
                    s1=rss.getString(1);
                    s2=rss.getString(2);s3=rss.getString(3);
                     System.out.println("S1--"+s1+"S2--"+s2+"S3--"+s3);
                    if(s1.contains(key)||s2.contains(key)||s3.contains(key)){
                        s1=s1.trim();
                        values.add(i, s1);
                        i++;
                        System.out.println("SS!"+s1);
                //        jComboBox1.addItem(s1);
                     
                    
                    }
                    
                }
               
        }
          catch(Exception e){}
        jList1.setListData(values.toArray());
                 jList1.addListSelectionListener(new ListSelectionListener()
               {                    
                   @Override
                   public void valueChanged(ListSelectionEvent lse) {
                       
                      String[] video_name={jList1.getSelectedValue().toString()}; 
                      video_name[0]="file:///D:/pcs/"+jList1.getSelectedValue().toString()+".mp4";
                      MediaPlayer.main(video_name);
                   }

               });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); 
        Home.main(uname);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String username) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(videos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(videos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(videos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(videos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        uname=username;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new videos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
